### ISSUE TITLE
Repeater in inline form shifting focus after clicking textfield

### ISSUE THREAD

**Issue by Piyushkhullar** [blackbaud/skyux-lists#100]
### Expected behavior
It should allow to edit the textbox after clicking

### Actual behavior
Clicking on textbox(most of the time 2nd one) shift the focus to outer div

### Steps to reproduce
1. Go to (https://developer.blackbaud.com/skyux/components/inline-form) 
2. Go to Repeater using inline forms section demo
3. click on edit button and then click on second textfield(Note) 
4. It shifted the focus even clicking on it multiple times

### Severity
Medium

### Impact
Medium

**Comment by Blackbaud-AlexKingman** [comment]
Hi @Piyushkhullar thanks for filing this issue.

After looking more into this, we believe focus issues were resolved in `@skyux/lists` version `3.7.1`. We ran some tests and it appears your particular scenario is also fixed.

Closing for now. If you are still experiencing trouble after updating to `3.7.1`, please let us know! Thanks.
