### ISSUE TITLE
Infinite scroll needs a way to jump back to the top of the list

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-lists#103]
### Expected behavior
As in SKYUX1 lists, there is a bar with a "back to top" action that appears at the bottom of the page when the list is scrolled.

### Actual behavior
User has to manually scroll back up to the top of the list.

**Comment by Blackbaud-ToddRoberts** [comment]
From FE NXT team.

They have a lot of long lists of data so this is a particularly important problem for them.

**Comment by Blackbaud-AlexKingman** [comment]
Look into how this should impact summary-action-bar.

**Comment by Blackbaud-AlexKingman** [comment]
There are a couple challenges this will introduce:

1. Currently, the infinite scroll component has no way to know what "Top" is. We'll have to create a new input for the consumer to define it.
2. The current UX pattern for a "back to top" button would be to replicate the summary action bar design, which is fixed to the bottom of the screen. In many cases, you could have an infinite scroll list along with a summary action bar, potentially causing 2 items to be fixed to the bottom. We need to introduce a "dock manager service" to handle the positioning of these fixed items so they don't overlap.

As these challenges will take some considerable time and effort to fix, we need to have more discussions around the priority of this feature.

**Comment by Blackbaud-AlexKingman** [comment]
Component released in `skyux-layout@3.8.0`. Docs to be released soon. Follow progress here: https://github.com/blackbaud/skyux-layout/pull/87
