### ISSUE TITLE
Repeater: Reorderable repeater `orderChange` event not showing new order upon drag/drop

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux-lists#132]
### Expected behavior
* Drag repeater item to new location
* `orderChange` event should be called with list of `tag` objects in new order
### Actual behavior
* `orderChange` event is called with original order of `tag` objects
### Steps to reproduce
* set up repeater with `[reorderable]=true`
* drag drop items
* observe `orderChange` call

**Comment by Blackbaud-TrevorBurch** [comment]
In version `3.8.5`
