### ISSUE TITLE
Repeater component overwrites the active index passed into it

### ISSUE THREAD

**Issue by Blackbaud-AliRashed** [blackbaud/skyux-lists#145]
Here's a stackblitz reproducing the issue: https://stackblitz.com/edit/angular-p5pxxr-jdh9ny?file=src/app/app.component.ts

We noticed this when implementing a confirmation modal when selecting a new repeater item where the repeater item feeds into a form.

### Expected behavior 
The repeater component keeps the original index selected if the parent component hasn't updated the activeIndex (in the case of the user deciding they don't actually want to navigate away from the repeater item they had selected).

### Actual behavior
The repeater component chooses the new element regardless of what the value of activeIndex in parent component is.

### Steps to reproduce
In the above stackblitz: 

- select a repeater element
- edit it in the form down below
- try to switch to a new element and then choose the 'Keep working' option when the confirmation modal pops up
- Observe that the data in the form stays the same (that's expected/desired), but that the repeater component has activated the new element.

### Impact
We haven't found a good workaround yet, and this is needed as a part of the SKYUX3 Migration effort for RENXT's Batch SPA (which is being rewritten for compliance reasons).

**Comment by Blackbaud-AliRashed** [comment]
Additionally, we found a similar issue with controlling the activated repeater item in the same project (though we don't have a stackblitz for this one). It seems like it might be related to this issue as well.

Copied from a discussion in Slack:

> We initially discovered this while working with a list that can dynamically change its size, which may or may not have an additional sky-repeater-item at the end of the repeater list (that holds content unrelated to the primary list). we want that last item to remain active and show as selected until another list member is selected, but as soon as the list starts changing size, we seem to be unable to control the highlighting effectively.

**Comment by Blackbaud-AliRashed** [comment]
After a discussion with @Blackbaud-ErikaMcVey in Slack, we found a workaround that mostly works (except for an edge case).

Erika's stackblitz here: https://stackblitz.com/edit/angular-p5pxxr-veozyn

We implemented this in our SPA and it works pretty well! However there is an edge case:

> It doesn't work if you click just to the left of the text, since that is the sky-repeater-item element

We discussed the possibility of updating our confirmation modal to be "Save/Discard changes" instead of "Keep working/Discard changes" to mirror something similar to what the split-view component does, but I think this issue would still apply in the save where the form is in an invalid state/can't be saved. In that case, I think we'd likely want to return to the originally activated element again as well.

**Comment by Blackbaud-SteveBrush** [comment]
The recommended pattern for your use-case is to use the split-view component. The demo on the docs demonstrates a save/discard changes scenario that will probably work for your requirements.
https://developer.blackbaud.com/skyux/components/split-view#demo

If that doesn't work, another option would be to use the inline-form component within your repeater.
https://developer.blackbaud.com/skyux/components/inline-form#demo
