### ISSUE TITLE
Port > Repeater reorder feature

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux-lists#18]
UX 1.x docs: https://skyux.developer.blackbaud.com/components/reorder/

**Comment by Blackbaud-Robfavre** [comment]
Church management has some configuration screens that are going to need this. Specifically, setting up the steps for a constituent's membership status and faith journey, and also grade levels, if we end up supporting those. The order of these will be important as they are steps in a process and they are going to be extremely specific to each individual church.

[https://blackbaud.invisionapp.com/share/BNQLH1AWG49#/345854230_denomination_Settings](url)

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.0`
