### ISSUE TITLE
Provide first class way to float controls to the right in Toolbar

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-lists#19]
@Blackbaud-ToddRoberts commented on [Fri Nov 16 2018](https://github.com/blackbaud/skyux2/issues/2176)

List Toolbar has a first class way to place elements on the right side of the toolbar. However, Toolbar does not even though placing controls on the right is part of the UX guidelines.

**Comment by Blackbaud-SteveBrush** [comment]
This was completed in https://github.com/blackbaud/skyux2/pull/1645.

Documentation: https://developer.blackbaud.com/skyux/components/list/toolbar#related-components

**Comment by Blackbaud-ToddRoberts** [comment]
This issue is for regular Toolbar, which AFAIK does not have the float right ability - it was only added to List Toolbar.

**Comment by Blackbaud-TrevorBurch** [comment]
Issue moved to [blackbaud/skyux-layout #19](https://github.com/blackbaud/skyux-layout/issues/19) via [**ZenHub**](https://www.zenhub.com/)
