### ISSUE TITLE
Applying filters to sky-list with list provider has race condition on refresh

### ISSUE THREAD

**Issue by Blackbaud-TomRamsey** [blackbaud/skyux-lists#191]
### Expected behavior

When applying filters to a paginated sky-list using a list provider and when the current page is not the first, then the sky-list should update to the first page of the recalculated results.

### Actual behavior

The sky-list is calling the list provider twice when filters are modified - once with no filters and once with the new filters.  This results in 2 service calls, and a race condition for which results render.  From a user's perspective, sometimes the list doesn't filter properly since the list doesn't appear to reflect filters.

### Severity
High

### Impact
High

[AB#1564654](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1564654)

**Comment by Blackbaud-DanMiller** [comment]
Current guidance is to migrate to data manager.
