### ISSUE TITLE
Repeater multiple expandMode doesn't collapse all by default

### ISSUE THREAD

**Issue by Blackbaud-CameronBeacham** [blackbaud/skyux-lists#200]
### Expected behavior
The [repeater](https://developer.blackbaud.com/skyux/components/repeater) docs specify that `[expandMode]="multiple"` 
> ... loads all repeater items in a collapsed state and allows users to expand and collapse them.

### Actual behavior
In the latest version of sky while it does let me open and collapse multiple items freely, the items do not start in a collapsed state. Is this a bug or am I supposed to be setting `[isExpanded]="false"` on each of my items if I want that functionality?

### Steps to reproduce
Create a repeater with `[expandMode]="multiple"` and multiple items. On load the items are not collapsed by default.

### Impact

[AB#1585841](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1585841)

**Comment by Blackbaud-SteveBrush** [comment]
This is a documentation issue. Thanks for filing!
