### ISSUE TITLE
Reorderable sky-repeater adding new item in top

### ISSUE THREAD

**Issue by blackbaud-vipin-singh** [blackbaud/skyux-lists#205]
### Expected behavior
Reordering the repeater item from the top item to the bottom item, and adding a new item in the repeater should add a newly added item in the last place.

### Actual behavior
Reordering the repeater item from top to bottom, adding a new item will show in the first place.

### Steps to reproduce
This issue is only in the prod build, locally it's working fine with skyux serve command.

Steps:
1. Add two items in the repeater.
2. Drag the first item on the second item.
3. Add the third item in the repeater.

Now It will show the last added item in the first place.
### Impact

[AB#1595498](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1595498)

**Comment by blackbaud-vipin-singh** [comment]
Slack thread for reference

https://blackbaud.slack.com/archives/C3TQ4C0KG/p1601904849112300

**Comment by Blackbaud-AlexKingman** [comment]
Fixed in `4.6.1`. Closing.
