### ISSUE TITLE
Modern Theme: Clicking directly on filter summary item's "X" does not dismiss the item

### ISSUE THREAD

**Issue by ThomasOrtiz** [blackbaud/skyux-lists#206]
### Expected behavior
- Clicking directly on a [filter summary item](https://developer.blackbaud.com/skyux/components/filter)'s X button should dismiss it.

### Actual behavior
- In Modern theme clicking directly on the X causes the pill/token to enlarge rather than dismiss the summary item.
- Workaround: 
  - If you click on the summary item the pill/token will be focused and enlarged. You can then click on the X and the filter will dismiss.
  - This causes users to do an additional click compared to the non-modern implementation.

### Steps to reproduce
1. Go to a modern theme SPA with a filter summary -- here's [Contributions' All Revenue page](https://host.nxt.blackbaud.com/jnl/revenue?svcid=tcs&envid=t-KnuvEzaWy0mMagoaSX5SRQ)
1. Apply a filter
1. Click directly on the X.
1. Notice that the pill/token enlarges quickly, the X is focused, but the filter is not dismissed.

**Comment by Blackbaud-SteveBrush** [comment]
We haven't applied the Modern theme to the tokens component yet; incoming!
