### ISSUE TITLE
sky-filter-summary-item no longer has right padding

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-lists#34]
### Expected behavior
Having multiple filters applied in a sky-list would provide a small spacing between them (on the right side of a filter)

### Actual behavior
Having multiple filters applied in a sky-list does not provide any spacing

### Steps to reproduce
Apply multiple filters to a sky-list
Note that the various filter bubbles have no padding between them

### Severity
Low

### Impact
Minimal annoyance in user interface for lists but something that has changed since a previous version where the filters had a slight spacing between them

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-LouisPujol just to help us track this down. Was this found after a Sky 2 -> Sky 3 migration or just a version upgrade?

**Comment by Blackbaud-LouisPujol** [comment]
After Sky 2 -> Sky 3 migration

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ToddRoberts could you help specify what the spacing here should be? This is most likely an Angular 7 spacing issue.

**Comment by Blackbaud-ToddRoberts** [comment]
5px (sky-margin-inline-compact)

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.3.1`
