### ISSUE TITLE
List search started from second page sometimes returns no results.

### ISSUE THREAD

**Issue by Blackbaud-ScottKavanagh** [blackbaud/skyux-lists#44]
### Expected behavior
Beginning a search from any page other than the first page should continue return all results.

### Actual behavior
There is a race condition when beginning a search a page other than the first page.  I believe this occurs when an paged offset is passed to a custom list provider.  

### Steps to reproduce
https://developer.blackbaud.com/skyux/components/list/overview
1. Navigate to example of "List with custom data provider"
2. Select the second page
3. Search using search text "lemons"
4. There are instances where this returns no results but should return 1.

We have duplicated in two separate SPAs and its likely occurs more when making real http requests.

### Severity
Low

### Impact
Low

Filed from bug https://blackbaud.visualstudio.com/Products/_workitems/edit/1198612

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/list-builder` version `3.5.2`
