### ISSUE TITLE
sky-filter-summary-item does not support overflow 

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [blackbaud/skyux-lists#46]
### Expected behavior
Having multiple filters applied in a sky-list should overflow onto another line. 

Each row should also have some padding/margin to distinguish the row from previous rows.

![image](https://user-images.githubusercontent.com/35976987/60298426-7c865300-98f8-11e9-9e4d-c024b05f6bee.png)

### Actual behavior
Having multiple filters applied in a sky-list does not overflow onto another line and instead go off the screen.

![image](https://user-images.githubusercontent.com/10877317/60297929-51e7ca80-98f7-11e9-93d7-27cd57aebeba.png)

### Steps to reproduce
Apply multiple filters to a sky-list until the filters go off the screen.

### Severity
Low

### Impact
Annoyance in user interface for lists as the user will have to scroll to the right once the amount of filters expand passed the horizontal view port of the screen.

**Comment by Blackbaud-SteveBrush** [comment]
Closing, as this behavior was addressed in a separate pull request (we will be releasing this fix shortly).
See: https://github.com/blackbaud/skyux-layout/pull/42

**Comment by Blackbaud-ThomasOrtiz** [comment]
@Blackbaud-SteveBrush 

While that PR fixes addresses the filters going off the screen with x overflow it doesn't satisfy what designed wanted (shown in my expected behavior picture). It doesn't satisfy design because the filters still go off the screen which means users can lose context of what the list is showing.

Is there any chance we can re-open the issue to get this expected behavior or should I continue manually over-riding the scss?

#### New behavior after the PR
![image](https://user-images.githubusercontent.com/10877317/61571902-35a5fc00-aa65-11e9-93c6-adbb751e4ade.png)

#### Expected Behavior
![image](https://user-images.githubusercontent.com/35976987/61572012-3f7c2f00-aa66-11e9-816d-20f8d2d6b8f4.png)

#### SCSS I used to achieve the expected picture
![image](https://user-images.githubusercontent.com/35976987/61571981-ef04d180-aa65-11e9-93f4-3874a8f59f66.png)

**Comment by Blackbaud-TrevorBurch** [comment]
We discussed this with our designer and came up with our current solution. @Blackbaud-ToddRoberts any thoughts on Thomas’ concerns?

**Comment by Blackbaud-ToddRoberts** [comment]
When we originally looked at scrolling vs wrapping for SKYUX 1, we decided that the potential downside of wrapping (the contents of the list getting pushed way down the page if a lot of filters are applied) outweighed the upside of all the filters being visible. This change brought the functionality in line with UX 1. Visually searching through the applied filter tokens is an inefficient way to figure out the full context, so from that standpoint there is not much difference between scrolling and wrapping. There is a project going on right now with some people on the UX team to redo the way filters work, so the implementation will be changing at some point anyway.
