### ISSUE TITLE
Repeater caret shows when new item added and expandMode="none"

### ISSUE THREAD

**Issue by GaleDragon** [blackbaud/skyux-lists#50]
### Expected behavior
When a repeater has `expandMode="none"` and an item has been added, the caret to collapse and expand does not show at all. 

### Actual behavior
When a repeater has `expandMode="none"` and an item has been added, the caret to collapse and expand shows, but disappears when on a mouse click. 
Maybe related, but if a list is entirely replaced the carets show briefly and then are hidden.

### Steps to reproduce
A reproduction actually appears in the documentation example - https://developer.blackbaud.com/skyux/components/repeater

1. Set expandMode to "none"
2. Click "Add item"
3. See the caret on the far right appear, in contradiction to the expandMode
4. On element click, caret disappears.

### Severity
Medium I suppose.

### Impact
Functionality isn't affected, but it sure looks weird.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.4.1`
