### ISSUE TITLE
I'd like to be able to get a count of rows in my <sky-list> that reflects applied searches and filters

### ISSUE THREAD

**Issue by christinebrandel** [blackbaud/skyux-lists#59]
### Expected behavior
On my sky-list I show a count of how many rows remain after search criteria and filters are applied.  To do this, I had to use the searchApply function, which is only available on sky-toolbar-item.  I'd like to have the same functionality on sky-list-toolbar-item.

### Impact
I have to use both <sky-toolbar> and <sky-list-toolbar> components on my page to get the desired behavior

**Comment by Blackbaud-SteveBrush** [comment]
We're not seeing the `searchApply` event emitter on the `<sky-toolbar-item>` component. Is this the correct component?

**Comment by christinebrandel** [comment]
Data

**Comment by Blackbaud-AlexKingman** [comment]
The recommended approach here is to utilize the `dataProvider`. That will give you access to the search data, so you should be able to easily get a count.
