### ISSUE TITLE
Repeater rows with no content should not show expand chevron or be clickable

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-lists#65]
### Expected behavior
When using a repeater with `expandMode` of `single` or `multiple`, for rows that do not have any "content", the expand chevron should be hidden and the row should not be clickable (basically, it should treat that row as if `expandMode` was `none`.

### Actual behavior
Currently, the row with no content still shows the expand chevron and appears clickable.  When you click on the row, the chevron changes, but nothing happens.  This could be confusing to users.

### Steps to reproduce
1. Add a repeater with `expandMode` set to `single` or `multiple`.
2. Add two rows that both use `sky-repeater-item-title`.
    1. The first row should use the `sky-repeater-item-content` tag and contain some text data inside it.
    2. The second row should NOT use the `sky-repeater-item-content` tag.
3. Notice the second row shows the expand chevron and is clickable even though it does not contain any "content".

### Severity
Low

### Impact
It could be confusing to users that the row appears clickable but actually doesn't do anything.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-KrisMahon Could you help me understand the scenario where you have some items with content and some without?

**Comment by Blackbaud-KrisMahon** [comment]
Just following up on the conversation we had a few weeks ago and documenting some of it.  We have a situation where our repeater contains 3 different types of records:  1) a boolen record, 2) a codetable-like record, 3) a text record.  For boolean and codetable-like records, we will display all the options as the content of the repeater.  But for text records, we will have too many random text strings in the repeater content, and instead we'd just like to display nothing and have the repeater row not expandable.  To workaround the issue (which isn't horrible), we've come up with some information text to show in the repeater content for text records.

![image](https://user-images.githubusercontent.com/12037520/66211031-252b1800-e689-11e9-96a4-c6e0ba923601.png)
