### ISSUE TITLE
Repeater isSelected property does not support two way binding

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-lists#68]
### Expected behavior

The documentation for the repeater item component states that the isSelected property will be updated on the model provided.

```
Indicates whether the repeater item's checkbox is selected. When users select the repeater item, the specified property on your model is updated accordingly. This property accepts boolean values.
```

### Actual behavior

The component does not update the model when an item is checked/unchecked

### Steps to reproduce

1. Create a repeater component
2. Bind the `isSelected` property of a repeater item to a model property
3. Check/uncheck the item
4. Notice the model's property does not get updated

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.0`
