### ISSUE TITLE
Repeater checkbox is not vertically aligned correctly

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-lists#7]
<img width="643" alt="screen shot 2018-12-04 at 12 43 52 pm" src="https://user-images.githubusercontent.com/12497062/49463861-70ee0600-f7c7-11e8-9416-3354d6f919c5.png">

From Todd Roberts: The checkbox should be aligned with the repeater title.

**Comment by Blackbaud-TrevorBurch** [comment]
Released in `2.35.0`
