### ISSUE TITLE
Repeater errors when initialized with no items

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-lists#89]
Due to the block of code starting at line 142 of the repeater component, when a repeater is initialized with no items and error is thrown due to this block trying to access `tabIndex` of the first repeater item (which does not exist)

**Comment by Blackbaud-AlexKingman** [comment]
On further investigation, this was a timing issue from a unit test. It does not appear to be happening in production code. Closing for now.
