### ISSUE TITLE
Form fields inside a repeater immediately lose focus

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-lists#95]
### Expected behavior

When I click a form field inside a repeater view, the field should focus.

### Actual behavior

The field gains focus and immediately loses it. The field cannot keep focus. I believe the entire repeater item is focused due to the blue highlight.

### Steps to reproduce

1. Use the code sample provided below
1. Click the text box
1. Note that the field turns red and the cursor is not in the field

```
      <sky-repeater>
        <sky-repeater-item>
          <sky-repeater-item-content>
            <div class="sky-form-group">
              <label class="sky-control-label">Name</label>
              <input type="text" required class="sky-form-control">
            </div>
          </sky-repeater-item-content>
        </sky-repeater-item>
      </sky-repeater>
```

This occurs when using an inline form as well.

### Severity

High - this prevents use of a form within a repeater.

### Impact

This impacts any repeater that contains form fields.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.7.1`

**Comment by Blackbaud-ChristiSchneider** [comment]
Thanks! I can use the fields now. Not sure if this is related, and definitely not high impact, but you can't tab around the fields in the repeaters either. Tab focus only works on the elements outside of the repeater.
