### ISSUE TITLE
Repeater shows strange highlighting artifacts when item is selected

### ISSUE THREAD

**Issue by Blackbaud-BrianBlanchard** [blackbaud/skyux-lists#98]
### Expected behavior
Highlighting selects item correctly.

### Actual behavior
Selecting an item shows strange artifacts (from demo page): 

![image](https://user-images.githubusercontent.com/23219799/70159443-e9abca80-1686-11ea-9ef8-d9d05ccf1687.png)

From another SPA: 
![image](https://user-images.githubusercontent.com/23219799/70159498-01834e80-1687-11ea-89ab-a966ffb5c274.png)

### Steps to reproduce

Add items to demo component, select an item, issue is reproduced. 
 https://developer.blackbaud.com/skyux/components/repeater

### Severity

Low

### Impact

Cosmetic

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-BrianBlanchard do you know if this is only happening on dynamically added items? That is what it appears to be happening to me in my very limited testing here.

**Comment by Blackbaud-BrianBlanchard** [comment]
I don't think so - it seems that it only starts to occur once you have about 5 items in the list.

**Comment by Blackbaud-AlexKingman** [comment]
It looks like this artifact is related to the CSS `float` from the demo. Using more updated styles (`flex-box`) should avoid this. We'll update the demo to reflect that.
