### ISSUE TITLE
Inconsistent spacing when chevron is hidden

### ISSUE THREAD

**Issue by Blackbaud-BrianBlanchard** [blackbaud/skyux-lists#99]
### Expected behavior

When a chevron is hidden in a list repeater, the spacing should be consistent with rows that are displaying a chevron

### Actual behavior

Spacing is smaller when chevron is hidden:

![image](https://user-images.githubusercontent.com/23219799/70160297-46f44b80-1688-11ea-9218-5db7bdd78ca9.png)

### Steps to reproduce

Create a list repeater, with multiple rows, and hide chevrons for a few rows, notice the space is 7 pixels shorter for rows without a chevron

### Severity

Low

### Impact

Cosmetic

**Comment by Blackbaud-SteveBrush** [comment]
I noticed that the dotted line between each repeater item does not continue beneath the context menu, as it does in our code demo:
https://developer.blackbaud.com/skyux/components/repeater#demo

If you implement the context menu in the way described by the demo, do you still see the padding discrepancy?

**Comment by Blackbaud-BrianBlanchard** [comment]
Nice catch.  Yes, that does seem to fix the padding, but the text is no longer aligned in the center of the list

![image](https://user-images.githubusercontent.com/23219799/70171078-01417e00-169c-11ea-8f76-1db8e2a9716c.png)
